name: Trigger Production Pipeline

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    name: Production Pipeline 
    uses: bandwidth-gig-guide/devops/.github/workflows/pipeline-production.yaml@main
    permissions:
      contents: write
      packages: write
    secrets:
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      DO_HOST: ${{ secrets.DO_HOST }}
      DO_USER: ${{ secrets.DO_USER }}
      DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
